#!/usr/bin/env python3
"""Generate a markdown audit report from findings JSON files.

Usage:
  python3 report.py --findings findings/ --out AUDIT_REPORT.md
"""

import argparse
import json
import pathlib
from collections import defaultdict
from datetime import date

RISK_ORDER = {"low": 0, "medium": 1, "high": 2}

CTA_FOOTER = """
---

*Generated by [CloudCost](https://github.com/codewithzhiva/cloudcost) — the open-source
AWS audit that found $370K/year on a Fortune-500 account.*

**Found savings you don't want to implement yourself?** I do this on gain-share:
no savings, no fee. → [book a call](https://calendly.com/shivaroopan)
"""


CONTEXT_FILES = {"spend.json"}  # context blobs, not Finding lists
BENCHMARKS_FILE = pathlib.Path(__file__).resolve().parents[1] / "reference" / "benchmarks.json"

BAND_BOUNDS = [(0, 5_000, "0-5k"), (5_000, 20_000, "5k-20k"),
               (20_000, 50_000, "20k-50k"), (50_000, float("inf"), "50k+")]


def load_findings(path: pathlib.Path):
    findings = []
    files = [path] if path.is_file() else sorted(path.glob("*.json"))
    for f in files:
        if f.name in CONTEXT_FILES:
            continue
        findings.extend(json.loads(f.read_text()))
    return findings


def load_spend(path: pathlib.Path):
    if path.is_file():
        path = path.parent
    spend_file = path / "spend.json"
    return json.loads(spend_file.read_text()) if spend_file.exists() else None


def fmt_usd(x: float) -> str:
    return f"${x:,.0f}"


def benchmark_section(spend, monthly_savings) -> list:
    """Renders only when reference/benchmarks.json exists (>= 10 real audits)."""
    if not BENCHMARKS_FILE.exists() or not spend:
        return []
    bm = json.loads(BENCHMARKS_FILE.read_text())
    avg = spend["avg_monthly_total"]
    band = next(label for lo, hi, label in BAND_BOUNDS if lo <= avg < hi)
    stats = bm.get("bands", {}).get(band)
    if not stats or not avg:
        return []
    your_pct = monthly_savings / avg * 100
    return [
        "## How you compare",
        "",
        f"Across {bm['audit_count']} audits of companies in your spend band ({band}/mo): "
        f"median waste is **{stats['median_waste_pct']}%** of the bill; the leanest quartile "
        f"runs at **{stats['top_quartile_waste_pct']}%**. This audit found **{your_pct:.0f}%** "
        f"in yours.",
        "",
    ]


def spend_header(spend, monthly_savings) -> list:
    months = spend["months"]
    totals = spend["total_by_month"]
    avg = spend["avg_monthly_total"]
    first, last = totals[months[0]], totals[months[-1]]
    trend = "rising" if last > first * 1.05 else "falling" if last < first * 0.95 else "flat"
    pct_of_bill = (monthly_savings / avg * 100) if avg else 0

    lines = [
        "## Your spend, in context",
        "",
        f"Average bill: **{fmt_usd(avg)}/month**, {trend} over the last {len(months)} full months "
        f"({' → '.join(fmt_usd(totals[m]) for m in months)}).",
        "",
        f"**The findings below are {pct_of_bill:.0f}% of your monthly bill.**",
        "",
        "| Top services (avg/mo) | Cost |",
        "|---|---|",
    ]
    lines += [f"| {s['service']} | {fmt_usd(s['avg_monthly'])} |" for s in spend["top_services"]]
    lines.append("")
    return lines


def generate(findings, spend=None) -> str:
    findings.sort(key=lambda f: (-f["estimated_monthly_savings"], RISK_ORDER.get(f["risk"], 1)))
    monthly = sum(f["estimated_monthly_savings"] for f in findings)
    cleared = sum(1 for f in findings if f.get("clearances"))
    blocked = sum(1 for f in findings if f["risk"] == "high")

    by_type = defaultdict(list)
    for f in findings:
        by_type[f["resource_type"]].append(f)

    lines = [
        "# AWS Cost Audit Report",
        "",
        f"*{date.today().isoformat()} — {len(findings)} findings: "
        f"{cleared} safety-cleared, {blocked} blocked by live references*",
        "",
        f"## Estimated savings: {fmt_usd(monthly)}/month ({fmt_usd(monthly * 12)}/year)",
        "",
        "Estimates use us-east-1 list prices; regional prices vary ~±20%. "
        "Each finding includes evidence and step-by-step remediation with a risk rating. "
        "✅ **Cleared** findings passed automated safety cross-checks (AMI references, "
        "route tables, Route53 records) — flagged *and verified*, not just flagged.",
        "",
    ]
    if spend:
        lines += spend_header(spend, monthly)
    lines += benchmark_section(spend, monthly)
    lines += [
        "## Summary by resource type",
        "",
        "| Resource type | Count | Est. monthly savings |",
        "|---|---|---|",
    ]
    for rtype, items in sorted(by_type.items(),
                               key=lambda kv: -sum(i["estimated_monthly_savings"] for i in kv[1])):
        subtotal = sum(i["estimated_monthly_savings"] for i in items)
        lines.append(f"| {rtype} | {len(items)} | {fmt_usd(subtotal)} |")

    lines += ["", "## Findings (highest savings first)", ""]
    for i, f in enumerate(findings, 1):
        lines += [
            f"### {i}. {f['resource_type']} `{f['resource_id']}` — "
            f"{fmt_usd(f['estimated_monthly_savings'])}/mo",
            "",
            f"- **Region:** {f['region']}  ",
            f"- **Risk:** {f['risk']}  ",
            f"- **Evidence:** {f['evidence']}",
        ]
        for c in f.get("clearances", []):
            lines.append(f"- ✅ **Cleared:** {c}")
        lines += [
            "",
            "**Remediation:**",
            "",
        ]
        lines += [f"{n}. {step}" for n, step in enumerate(f["remediation_steps"], 1)]
        lines.append("")

    lines.append(CTA_FOOTER)
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--findings", default="findings/", help="findings dir or single JSON file")
    ap.add_argument("--out", default="AUDIT_REPORT.md")
    args = ap.parse_args()

    findings = load_findings(pathlib.Path(args.findings))
    if not findings:
        print("No findings found — run the collectors first.")
        return
    spend = load_spend(pathlib.Path(args.findings))
    pathlib.Path(args.out).write_text(generate(findings, spend))
    monthly = sum(f["estimated_monthly_savings"] for f in findings)
    print(f"Report written to {args.out}: {len(findings)} findings, "
          f"{fmt_usd(monthly)}/mo ({fmt_usd(monthly * 12)}/yr)")


if __name__ == "__main__":
    main()
